### PR TITLE
Rubocop

### PR DESCRIPTION
**Pull request by glasnt**
I've created a basic .rubocop.yml file, automatically run it, then manually completed some of it's recommendations. Each are three separate commits. 

We can use this across other projects, once we confirm that the standard file is inline with our style standards.

### CODE REVIEW

**Comment by nerdyness** [comment]
Ooops. I commented on the individual commits, not this PR.

**Comment by glasnt** [comment]
> I wish it moved "#{variable}" to "#{ variable }" but maybe that's something we can add?

Either I'm missing something, or this isn't an option in Rubocop. See https://gist.github.com/glasnt/ee9aff3d62ddeb306194

/me grabs snorkel and goes code diving.

**Comment by glasnt** [comment]
So rubocop PR#1836 introduces string interpolation detection and fixing. As soon as rubocop is bumped past 0.31, it'll be too simple to run it over this code base, with the .rubocop.yml file in this PR, and fix all the code. 
I'll create a new branch with the yml file and it's autofixing once a) rubocop is bumped, b) index-page branch things are fixed (current major pending change)

**Comment by glasnt** [comment]
Rubocop v0.32 is now a thing. This should be fixable robotically

**Comment by nerdyness** [comment]
```
$ gem list rubocop

*** LOCAL GEMS ***

rubocop (0.25.0)
sk@diffie:~/bp/playground/assemblage/instance-shutdown-scheduling (master) $ gem update rubocop                                             
Updating installed gems
Updating rubocop
Fetching: parser-2.2.2.5.gem (100%)
Fetching: powerpack-0.1.1.gem (100%)
Fetching: astrolabe-1.3.0.gem (100%)
Fetching: rubocop-0.32.0.gem (100%)
Successfully installed parser-2.2.2.5
Successfully installed powerpack-0.1.1
Successfully installed astrolabe-1.3.0
Successfully installed rubocop-0.32.0
Gems updated: parser, powerpack, astrolabe, rubocop
sk@diffie:~/bp/playground/assemblage/instance-shutdown-scheduling (master) $ rbenv rehash
sk@diffie:~/bp/playground/assemblage/instance-shutdown-scheduling (master) $ rubocop --version
0.32.0
```
:laughing:
Let the games begin :+1:

**Comment by glasnt** [comment]
Seen #32 since this branch is well out of date now.

**Pull request closed without merging**
