### PR TITLE
Make the date persistant between tabs

### PR DESCRIPTION
**Pull request by glasnt**
Resolves issue #4

I thought it'd be better to keep the URI style, and just change the functionality of the top links to use the start/end date in their urls. This achieves the required functionality of the request without changing the structure of the website, and keeping it query-string free.

I've also enabled the default 'home' functionality on the navbar-brand, which takes the user back to "/", which is the default entry point. Small css change because bootstrap thinks that a link in a navbar-brand should be glaringly ugly.

### CODE REVIEW

**Comment by Hobbsee** [comment]
Looks great and works well, but I notice Pigeonhole at the top goes blue before you mouse over and click on it.

Any chance you could stop that too?  :)

screen shot 2015-04-17 at 7 15 17 pm

**Comment by glasnt** [comment]
Tis but a css.

It will be fixed.

**Comment by glasnt** [comment]
@Hobbsee should be fine for you now. Let me know if Safari is still being silly.

**Comment by Hobbsee** [comment]
Looks great!

**Comment by nerdyness** [comment]
:+1:

**Pull request merged**
